import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import { addDoc, collection, doc, getDoc, getFirestore, serverTimestamp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyAPkjFAzWhxaAnsfxd4PGQsFCkurV0u6f4',authDomain:'device-streaming-23f6b787.firebaseapp.com',projectId:'device-streaming-23f6b787',storageBucket:'device-streaming-23f6b787.firebasestorage.app',messagingSenderId:'1084466489845',appId:'1:1084466489845:web:3f1cb241ed0f39914858bc'};
const questionBank=[
  {id:'q1',title:'Pensando na rotina da empresa hoje, o que mais dificulta o trabalho da gestão?',help:'Conte situações concretas do dia a dia.',type:'open'},
  {id:'q2',title:'Qual atividade ou processo mais consome tempo da sua equipe atualmente?',help:'Descreva onde a equipe dedica mais tempo e por quê.',type:'open'},
  {id:'q3',title:'Existe alguma tarefa que depende muito de uma pessoa específica para funcionar? Conte como acontece.',help:'Pense no que acontece quando essa pessoa está ocupada ou ausente.',type:'open'},
  {id:'q4',title:'Quando o movimento ou a demanda aumenta, qual parte da operação costuma apresentar mais dificuldade?',help:'Relate gargalos, atrasos ou pontos em que o fluxo deixa de funcionar bem.',type:'open'},
  {id:'q5',title:'Existe alguma atividade repetitiva que sua equipe precisa executar várias vezes durante o dia?',help:'Considere atendimentos, registros, conferências, mensagens ou outras rotinas.',type:'open'},
  {id:'q6',title:'O que sua equipe deixa de fazer ou faz com menos atenção por estar ocupada com outras tarefas?',help:'Busque entender o que está sendo deixado de lado por falta de tempo ou capacidade.',type:'open'},
  {id:'q7',title:'Qual processo você sente que poderia funcionar de uma maneira mais simples ou eficiente?',help:'Descreva o processo e o que hoje torna essa atividade difícil ou demorada.',type:'open'},
  {id:'q8',title:'Se você pudesse resolver hoje apenas um problema da gestão ou da operação da empresa, qual resolveria primeiro?',help:'Explique por que esse problema seria sua prioridade.',type:'open'}
];
let questions=[...questionBank];
const state=JSON.parse(localStorage.getItem('dg-state')||'{}');
if(state.schemaVersion!==3){state.answers={};state.schemaVersion=3;localStorage.setItem('dg-state',JSON.stringify(state));}
const $=id=>document.getElementById(id);
const saveButtons=()=>[$('save-diagnostic'),$('mobile-save-diagnostic')].filter(Boolean);
const esc=v=>String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let db,firebaseAuth,firebaseReady=false;

async function connectFirebase(){try{const app=initializeApp(firebaseConfig);db=getFirestore(app);firebaseAuth=getAuth(app);await signInAnonymously(firebaseAuth);firebaseReady=true;await loadQuestionConfig();}catch(error){console.warn('Firebase ainda não está pronto:',error.code||error.message);}}
function normalizeConfiguredQuestion(question,index=0){return {id:String(question?.id||`q_config_${index}`),title:String(question?.title||'').trim(),help:String(question?.help||'').trim(),type:'open',active:question?.active!==false,order:Number.isFinite(question?.order)?question.order:index};}
async function loadQuestionConfig(){try{const snapshot=await getDoc(doc(db,'settings','diagnostic'));if(snapshot.exists()){const data=snapshot.data();if(Number(data.schemaVersion)>=3&&Array.isArray(data.questions)&&data.questions.length){const configured=data.questions.map(normalizeConfiguredQuestion).filter(question=>question.active&&question.title);if(configured.length)questions=configured;else questions=[...questionBank];}else{questions=[...questionBank];}}else{questions=[...questionBank];}renderQuestions();update();}catch(error){console.warn('Não foi possível carregar a configuração de perguntas:',error.code||error.message);questions=[...questionBank];renderQuestions();update();}};questions.forEach(question=>{const answer=state.answers?.[question.id];if(!answer?.choice||!question.options.includes(answer.choice))return;(question.tags?.[answer.choice]||[]).forEach(tag=>scores[tag]=(scores[tag]||0)+1);});return Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,3);}
function renderQuestions(){$('questions').innerHTML=questions.map((q,i)=>`<article class="question-card"><div class="section-kicker">${String(i+2).padStart(2,'0')}</div><div class="section-content"><div class="question-head"><span class="question-number">PERGUNTA ${i+1}</span><div><h3 class="question-title">${esc(q.title)}</h3>${q.help?`<p class="question-help">${esc(q.help)}</p>`:''}</div></div><label class="answer-field">Resposta<textarea data-answer="${q.id}" placeholder="Registre a resposta com as palavras do entrevistado.">${esc(state.answers?.[q.id]?.text||'')}</textarea></label><label class="note secondary-note">Observação do entrevistador <textarea data-note="${q.id}" placeholder="Anote contexto, impacto percebido ou uma oportunidade que mereça aprofundamento.">${esc(state.answers?.[q.id]?.note||'')}</textarea></label></div></article>`).join('');const kicker=$('analysis-kicker');if(kicker)kicker.textContent=String(questions.length+2).padStart(2,'0');}
function save(){['owner','store','segment','date','final-note'].forEach(id=>state[id]=$(id).value);localStorage.setItem('dg-state',JSON.stringify(state));$('autosave-status').textContent='Rascunho salvo neste aparelho';update();}
function update(){const answered=questions.filter(question=>String(state.answers?.[question.id]?.text||'').trim()).length;const complete=answered===questions.length;saveButtons().forEach(button=>{button.disabled=!complete;button.setAttribute('aria-disabled',String(!complete));button.title=complete?'Salvar diagnóstico':`Responda as ${questions.length-answered} pergunta${questions.length-answered===1?'':'s'} restante${questions.length-answered===1?'':'s'} para liberar o salvamento`;});$('progress-text').textContent=`${answered} de ${questions.length}`;$('progress-fill').style.width=`${questions.length?answered/questions.length*100:0}%`;$('progress-note').textContent=complete?'Entrevista completa. Revise as respostas e salve a pesquisa.':'Registre a fala do gestor com o máximo de fidelidade possível.';const recommendation=$('recommendations');if(recommendation)recommendation.innerHTML=answered?'<div class="recommendation"><strong>Escuta ativa em andamento</strong><span>As respostas abertas ajudam a revelar gargalos, tarefas manuais, dependências e oportunidades de melhoria sem induzir o entrevistado.</span></div>':'<p class="empty-state">As respostas serão reunidas em um resumo fiel da conversa.</p>';const lines=[`PULSO CHECK ENTERPRISE${state.store?' — '+state.store:''}`,state.owner?`Responsável: ${state.owner}`:'',state.segment?`Segmento: ${state.segment}`:'','',...questions.map((q,i)=>{const answer=state.answers?.[q.id];return answer?.text?.trim()?`${i+1}. ${q.title}\nResposta: ${answer.text.trim()}${answer.note?.trim()?'\nObservação do entrevistador: '+answer.note.trim():''}`:'';}).filter(Boolean),state['final-note']?'\nObservação final e próximos passos:\n'+state['final-note']:''].filter(Boolean);$('summary-box').textContent=lines.join('\n\n');}
function diagnosticPayload(){return {business:{owner:state.owner||'',name:state.store||'',segment:state.segment||'',interviewDate:state.date||''},answerMode:'open',answers:questions.map(question=>({questionId:question.id,question:question.title,response:String(state.answers?.[question.id]?.text||'').trim(),note:String(state.answers?.[question.id]?.note||'').trim()})),finalNote:state['final-note']||''};}
async function persistDiagnostic(){const answered=questions.filter(question=>String(state.answers?.[question.id]?.text||'').trim()).length;if(answered!==questions.length){$('autosave-status').textContent=`Faltam ${questions.length-answered} respostas para salvar`;return;}if(!firebaseReady||!firebaseAuth.currentUser){$('autosave-status').textContent='Conexão com o banco pendente. Verifique a configuração Firebase.';return;}const buttons=saveButtons();buttons.forEach(button=>{button.disabled=true;button.textContent='Salvando...';});try{const payload=diagnosticPayload();await addDoc(collection(db,'diagnostics'),{schemaVersion:3,status:'new',createdAt:serverTimestamp(),clientCreatedAt:new Date().toISOString(),...payload,source:'pulso-check-enterprise'});buttons.forEach(button=>button.textContent='Diagnóstico salvo');$('autosave-status').textContent='Diagnóstico salvo no painel com sucesso';setTimeout(()=>saveButtons().forEach(button=>{button.disabled=false;button.textContent='Salvar novo diagnóstico';}),1600);}catch(error){console.error(error);saveButtons().forEach(button=>{button.disabled=false;button.textContent='Tentar novamente';});$('autosave-status').textContent='Não foi possível salvar o diagnóstico. Tente novamente.';}}
['owner','store','segment','date','final-note'].forEach(id=>{$(id).value=state[id]||'';$(id).addEventListener('input',save);$(id).addEventListener('change',save);});
$('questions').addEventListener('input',e=>{if(e.target.matches('[data-answer]')){const i=e.target.dataset.answer;state.answers??={};state.answers[i]??={};state.answers[i].text=e.target.value;save();return;}if(e.target.matches('[data-note]')){const i=e.target.dataset.note;state.answers??={};state.answers[i]??={};state.answers[i].note=e.target.value;save();}});
$('copy-summary').addEventListener('click',async()=>{await navigator.clipboard.writeText($('summary-box').textContent);$('copy-summary').textContent='Resumo copiado';setTimeout(()=>$('copy-summary').textContent='Copiar resumo',1500);});
saveButtons().forEach(button=>{button.textContent='Salvar diagnóstico';button.addEventListener('click',persistDiagnostic);});
$('reset').addEventListener('click',()=>{if(confirm('Limpar todas as respostas desta entrevista?')){localStorage.removeItem('dg-state');location.reload();}});
renderQuestions();update();connectFirebase();
