import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import { addDoc, collection, doc, getDoc, getFirestore, serverTimestamp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyAPkjFAzWhxaAnsfxd4PGQsFCkurV0u6f4',authDomain:'device-streaming-23f6b787.firebaseapp.com',projectId:'device-streaming-23f6b787',storageBucket:'device-streaming-23f6b787.firebasestorage.app',messagingSenderId:'1084466489845',appId:'1:1084466489845:web:3f1cb241ed0f39914858bc'};
const questionBank=[
  {id:'q1',title:'Qual é hoje o maior desafio do negócio?',help:'Escolha o ponto que mais impacta a operação.',options:['Organização do dia a dia','Vendas e clientes','Controle financeiro','Estoque e desperdício','Equipe e atendimento','Outro'],tags:{'Organização do dia a dia':['Processos e rotina'],'Vendas e clientes':['Vendas e relacionamento'],'Controle financeiro':['Financeiro e indicadores'],'Estoque e desperdício':['Estoque e compras'],'Equipe e atendimento':['Equipe e atendimento']}},
  {id:'q2',title:'Como as vendas, pedidos ou serviços são registrados?',help:'Entenda o nível de organização atual.',options:['Caderno / papel','WhatsApp','Planilha','Sistema','Não existe padrão'],tags:{'Caderno / papel':['Processos e rotina'],'WhatsApp':['Processos e rotina'],'Planilha':['Financeiro e indicadores'],'Não existe padrão':['Processos e rotina']}},
  {id:'q3',title:'A pessoa responsável consegue enxergar o resultado mensal?',help:'Lucro, custos e principais gastos.',options:['Sim, com clareza','Mais ou menos','Não consegue acompanhar'],tags:{'Mais ou menos':['Financeiro e indicadores'],'Não consegue acompanhar':['Financeiro e indicadores']}},
  {id:'q4',title:'Há perdas por erro, retrabalho ou falta de informação?',help:'Erros em pedidos, serviços, agenda, caixa ou comunicação.',options:['Frequentemente','Às vezes','Raramente'],tags:{'Frequentemente':['Processos e rotina'],'Às vezes':['Processos e rotina']}},
  {id:'q5',title:'Como são controlados materiais, produtos ou estoque?',help:'Se o negócio não trabalha com estoque, marque a última opção.',options:['De cabeça','Caderno ou planilha','Sistema','Não se aplica'],tags:{'De cabeça':['Estoque e compras'],'Caderno ou planilha':['Estoque e compras']}},
  {id:'q6',title:'Como novos clientes chegam ao negócio?',help:'Identifique a principal fonte atual.',options:['Indicação','Instagram / redes sociais','WhatsApp','Anúncios','Ponto físico','Não acompanho'],tags:{'Não acompanho':['Vendas e relacionamento']}},
  {id:'q7',title:'Existe acompanhamento dos clientes depois da compra?',help:'Retorno, fidelização, lembretes ou ofertas.',options:['Sim, organizado','Às vezes','Não'],tags:{'Às vezes':['Vendas e relacionamento'],'Não':['Vendas e relacionamento']}},
  {id:'q8',title:'Qual melhoria teria maior impacto nos próximos 90 dias?',help:'Use essa resposta para definir a prioridade.',options:['Vender mais','Organizar a operação','Reduzir custos','Controlar melhor o dinheiro','Melhorar o atendimento','Outro'],tags:{'Vender mais':['Vendas e relacionamento'],'Organizar a operação':['Processos e rotina'],'Reduzir custos':['Estoque e compras'],'Controlar melhor o dinheiro':['Financeiro e indicadores'],'Melhorar o atendimento':['Equipe e atendimento']}}
];
let questions=[...questionBank];
const insights={'Processos e rotina':'Há sinais de operação descentralizada. Priorize um fluxo simples, com registros claros e menos retrabalho.','Vendas e relacionamento':'Existe espaço para capturar oportunidades e manter contato com clientes depois da primeira compra.','Financeiro e indicadores':'A prioridade é dar visibilidade: vendas, custos, despesas e resultado em uma leitura rápida.','Estoque e compras':'O controle de materiais pode estar consumindo margem. O foco deve ser evitar falta, excesso e desperdício.','Equipe e atendimento':'Vale padronizar responsabilidades e comunicação para melhorar a experiência do cliente.'};
const state=JSON.parse(localStorage.getItem('dg-state')||'{}');
if(state.answers&&Object.keys(state.answers).some(key=>/^\d+$/.test(key))){const migrated={};Object.entries(state.answers).forEach(([key,value])=>{const question=questionBank[Number(key)];if(question)migrated[question.id]=value;});state.answers=migrated;localStorage.setItem('dg-state',JSON.stringify(state));}
const $=id=>document.getElementById(id);
const saveButtons=()=>[$('save-diagnostic'),$('mobile-save-diagnostic')].filter(Boolean);
const esc=v=>String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let db,firebaseAuth,firebaseReady=false;

async function connectFirebase(){try{const app=initializeApp(firebaseConfig);db=getFirestore(app);firebaseAuth=getAuth(app);await signInAnonymously(firebaseAuth);firebaseReady=true;await loadQuestionConfig();}catch(error){console.warn('Firebase ainda não está pronto:',error.code||error.message);}}
function normalizeConfiguredQuestion(question,index=0){const fallback=questionBank.find(item=>item.id===question?.id);const options=Array.isArray(question?.options)?question.options.map(option=>String(option).trim()).filter(Boolean):fallback?[...fallback.options]:[];return {id:String(question?.id||`q_config_${index}`),title:String(question?.title??fallback?.title??'').trim(),help:String(question?.help??fallback?.help??'').trim(),options,tags:question?.tags&&typeof question.tags==='object'?question.tags:(fallback?.tags||{}),active:question?.active!==false};}
async function loadQuestionConfig(){try{const snapshot=await getDoc(doc(db,'settings','diagnostic'));if(snapshot.exists()){const data=snapshot.data();if(Array.isArray(data.questions)&&data.questions.length){const configured=data.questions.map(normalizeConfiguredQuestion).filter(question=>question.active&&question.title&&question.options.length);if(configured.length)questions=configured;}else{const configuredIds=Array.isArray(data.activeQuestionIds)?data.activeQuestionIds:[];const configured=questionBank.filter(question=>configuredIds.includes(question.id));if(configured.length)questions=configured;}}renderQuestions();update();}catch(error){console.warn('Não foi possível carregar a configuração de perguntas:',error.code||error.message);questions=[...questionBank];renderQuestions();update();}}
function priorities(){const scores={};questions.forEach(question=>{const answer=state.answers?.[question.id];if(!answer?.choice||!question.options.includes(answer.choice))return;(question.tags?.[answer.choice]||[]).forEach(tag=>scores[tag]=(scores[tag]||0)+1);});return Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,3);}
function renderQuestions(){$('questions').innerHTML=questions.map((q,i)=>`<article class="question-card"><div class="section-kicker">${String(i+2).padStart(2,'0')}</div><div class="section-content"><div class="question-head"><span class="question-number">PERGUNTA ${i+1}</span><div><h3 class="question-title">${q.title}</h3><p class="question-help">${q.help}</p></div></div><div class="options">${q.options.map(o=>`<button class="option ${state.answers?.[q.id]?.choice===o?'selected':''}" data-q="${q.id}" data-o="${esc(o)}" type="button">${esc(o)}</button>`).join('')}</div><label class="note">Observação<textarea data-note="${q.id}" placeholder="Registre detalhes, exemplos ou uma frase importante da conversa.">${esc(state.answers?.[q.id]?.note||'')}</textarea></label></div></article>`).join('');}
function save(){['owner','store','segment','date','final-note'].forEach(id=>state[id]=$(id).value);localStorage.setItem('dg-state',JSON.stringify(state));$('autosave-status').textContent='Rascunho salvo neste aparelho';update();}
function update(){const answered=questions.filter(question=>question.options.includes(state.answers?.[question.id]?.choice)).length;const complete=answered===questions.length;saveButtons().forEach(button=>{button.disabled=!complete;button.setAttribute('aria-disabled',String(!complete));button.title=complete?'Salvar diagnóstico':`Responda as ${questions.length-answered} pergunta${questions.length-answered===1?'':'s'} restante${questions.length-answered===1?'':'s'} para liberar o salvamento`;});$('progress-text').textContent=`${answered} de ${questions.length}`;$('progress-fill').style.width=`${answered/questions.length*100}%`;$('progress-note').textContent=complete?'Diagnóstico completo. Salve-o para receber a análise personalizada.':'Continue registrando as respostas da conversa.';const ranked=priorities();$('recommendations').innerHTML=ranked.length?ranked.map(([tag])=>`<div class="recommendation"><strong>${tag}</strong><span>${insights[tag]}</span></div>`).join(''):'<p class="empty-state">Marque as respostas para receber uma recomendação de abordagem.</p>';const lines=[`PULSO CHECK ENTERPRISE${state.store?' — '+state.store:''}`,state.owner?`Responsável: ${state.owner}`:'',state.segment?`Segmento: ${state.segment}`:'','',...questions.map((q,i)=>state.answers?.[q.id]?.choice?`${i+1}. ${q.title}\nResposta: ${state.answers[q.id].choice}${state.answers[q.id].note?'\nObservação: '+state.answers[q.id].note:''}`:'').filter(Boolean),ranked.length?'\nPrioridades identificadas:\n'+ranked.map(([t])=>`• ${t}: ${insights[t]}`).join('\n'):'',state['final-note']?'\nPróximos passos:\n'+state['final-note']:''].filter(Boolean);$('summary-box').textContent=lines.join('\n\n');}
function diagnosticPayload(){const ranked=priorities().map(([name,score])=>({name,score,summary:insights[name]}));return {business:{owner:state.owner||'',name:state.store||'',segment:state.segment||'',interviewDate:state.date||''},answers:questions.map(question=>({questionId:question.id,question:question.title,choice:state.answers?.[question.id]?.choice||'',note:state.answers?.[question.id]?.note||''})),priorities:ranked,finalNote:state['final-note']||''};}
async function persistDiagnostic(){const answered=questions.filter(question=>question.options.includes(state.answers?.[question.id]?.choice)).length;if(answered!==questions.length){$('autosave-status').textContent=`Faltam ${questions.length-answered} respostas para salvar`;return;}if(!firebaseReady||!firebaseAuth.currentUser){$('autosave-status').textContent='Conexão com o banco pendente. Verifique a configuração Firebase.';return;}const buttons=saveButtons();buttons.forEach(button=>{button.disabled=true;button.textContent='Salvando...';});try{const payload=diagnosticPayload();await addDoc(collection(db,'diagnostics'),{schemaVersion:1,status:'new',createdAt:serverTimestamp(),clientCreatedAt:new Date().toISOString(),...payload,source:'pulso-check-enterprise'});buttons.forEach(button=>button.textContent='Diagnóstico salvo');$('autosave-status').textContent='Diagnóstico salvo no painel com sucesso';setTimeout(()=>saveButtons().forEach(button=>{button.disabled=false;button.textContent='Salvar novo diagnóstico';}),1600);}catch(error){console.error(error);saveButtons().forEach(button=>{button.disabled=false;button.textContent='Tentar novamente';});$('autosave-status').textContent='Não foi possível salvar o diagnóstico. Tente novamente.';}}
['owner','store','segment','date','final-note'].forEach(id=>{$(id).value=state[id]||'';$(id).addEventListener('input',save);$(id).addEventListener('change',save);});
$('questions').addEventListener('click',e=>{const b=e.target.closest('[data-q]');if(!b)return;const i=b.dataset.q;state.answers??={};state.answers[i]??={};state.answers[i].choice=b.dataset.o;renderQuestions();save();});
$('questions').addEventListener('input',e=>{if(!e.target.matches('[data-note]'))return;const i=e.target.dataset.note;state.answers??={};state.answers[i]??={};state.answers[i].note=e.target.value;save();});
$('copy-summary').addEventListener('click',async()=>{await navigator.clipboard.writeText($('summary-box').textContent);$('copy-summary').textContent='Resumo copiado';setTimeout(()=>$('copy-summary').textContent='Copiar resumo',1500);});
saveButtons().forEach(button=>{button.textContent='Salvar diagnóstico';button.addEventListener('click',persistDiagnostic);});
$('reset').addEventListener('click',()=>{if(confirm('Limpar todas as respostas desta entrevista?')){localStorage.removeItem('dg-state');location.reload();}});
renderQuestions();update();connectFirebase();
