import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import { collection, deleteDoc, doc, getDoc, getFirestore, onSnapshot, orderBy, query, serverTimestamp, setDoc } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyAPkjFAzWhxaAnsfxd4PGQsFCkurV0u6f4',authDomain:'device-streaming-23f6b787.firebaseapp.com',projectId:'device-streaming-23f6b787',storageBucket:'device-streaming-23f6b787.firebasestorage.app',messagingSenderId:'1084466489845',appId:'1:1084466489845:web:3f1cb241ed0f39914858bc'};
const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getFirestore(app);
const $=id=>document.getElementById(id); const esc=value=>String(value||'—').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])); const html=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const defaultQuestions=[
  {id:'q1',title:'Pensando na rotina da empresa hoje, o que mais dificulta o trabalho da gestão?',help:'Conte situações concretas do dia a dia.',type:'open'},
  {id:'q2',title:'Qual atividade ou processo mais consome tempo da sua equipe atualmente?',help:'Descreva onde a equipe dedica mais tempo e por quê.',type:'open'},
  {id:'q3',title:'Existe alguma tarefa que depende muito de uma pessoa específica para funcionar? Conte como acontece.',help:'Pense no que acontece quando essa pessoa está ocupada ou ausente.',type:'open'},
  {id:'q4',title:'Quando o movimento ou a demanda aumenta, qual parte da operação costuma apresentar mais dificuldade?',help:'Relate gargalos, atrasos ou pontos em que o fluxo deixa de funcionar bem.',type:'open'},
  {id:'q5',title:'Existe alguma atividade repetitiva que sua equipe precisa executar várias vezes durante o dia?',help:'Considere atendimentos, registros, conferências, mensagens ou outras rotinas.',type:'open'},
  {id:'q6',title:'O que sua equipe deixa de fazer ou faz com menos atenção por estar ocupada com outras tarefas?',help:'Busque entender o que está sendo deixado de lado por falta de tempo ou capacidade.',type:'open'},
  {id:'q7',title:'Qual processo você sente que poderia funcionar de uma maneira mais simples ou eficiente?',help:'Descreva o processo e o que hoje torna essa atividade difícil ou demorada.',type:'open'},
  {id:'q8',title:'Se você pudesse resolver hoje apenas um problema da gestão ou da operação da empresa, qual resolveria primeiro?',help:'Explique por que esse problema seria sua prioridade.',type:'open'}
];
let questionDraft=[], diagnostics=[], unsubscribeDiagnostics;
function dateOf(item){return item.clientCreatedAt?new Date(item.clientCreatedAt):item.createdAt?.toDate?.()||new Date();}
function formatDate(item){return dateOf(item).toLocaleDateString('pt-BR',{dateStyle:'short'})+' '+dateOf(item).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});}
function details(item){const answers=(item.answers||[]).map((answer,index)=>`${index+1}. ${answer.question}\nResposta: ${answer.response||answer.choice||'—'}${answer.note?`\nObservação do entrevistador: ${answer.note}`:''}`).join('\n\n');return `${item.business?.name||'Negócio não informado'}\nResponsável: ${item.business?.owner||'—'}\nSegmento: ${item.business?.segment||'—'}\n\n${answers}\n\nObservação final:\n${item.finalNote||'—'}`;}
function render(){const todayKey=new Date().toDateString();$('total').textContent=diagnostics.length;$('today').textContent=diagnostics.filter(item=>dateOf(item).toDateString()===todayKey).length;$('segments').textContent=new Set(diagnostics.map(item=>item.business?.segment).filter(Boolean)).size;$('rows').innerHTML=diagnostics.length?diagnostics.map((item,index)=>`<tr><td>${esc(formatDate(item))}</td><td><strong>${esc(item.business?.name)}</strong></td><td>${esc(item.business?.owner)}</td><td>${esc(item.business?.segment)}</td><td>${esc(item.answerMode==='open'?'Respostas abertas':((item.priorities||[]).map(priority=>priority.name).join(', ')||'—'))}</td><td><button data-detail="${index}">Ver</button> <button class="delete" data-delete="${index}">Excluir</button></td></tr>`).join(''):'<tr><td colspan="6">Ainda não há diagnósticos salvos.</td></tr>';}
function loadDiagnostics(){if(unsubscribeDiagnostics)unsubscribeDiagnostics();unsubscribeDiagnostics=onSnapshot(query(collection(db,'diagnostics'),orderBy('createdAt','desc')),snapshot=>{diagnostics=snapshot.docs.map(doc=>({id:doc.id,...doc.data()}));render();},error=>{$('rows').innerHTML='<tr><td colspan="6">Não foi possível carregar os diagnósticos. Confira as regras do Firestore.</td></tr>';console.error(error);});}
function cloneDefaults(){return defaultQuestions.map(question=>({...question,active:true}));}
function createQuestionId(){return 'q_custom_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);}
function normalizeQuestion(question,index=0){return {id:String(question?.id||createQuestionId()),title:String(question?.title||'').trim(),help:String(question?.help||'').trim(),type:'open',active:question?.active!==false,order:Number.isFinite(question?.order)?question.order:index};}
function renderQuestionConfig(){const list=$('question-list');list.innerHTML=questionDraft.map((question,index)=>`<article class='question-editor ${question.active?'':'inactive'}' data-id='${html(question.id)}'><div class='question-editor-top'><div><span class='question-index'>PERGUNTA ${index+1}</span><label class='active-switch'><input class='q-active' type='checkbox' ${question.active?'checked':''}><span>${question.active?'Ativa na pesquisa':'Oculta na pesquisa'}</span></label></div><button class='danger-btn q-delete' type='button'>Excluir</button></div><label>Texto da pergunta<input class='q-title' type='text' value='${html(question.title)}' placeholder='Digite a pergunta'></label><label>Texto de apoio <small>(opcional)</small><input class='q-help' type='text' value='${html(question.help)}' placeholder='Ex.: peça um exemplo concreto da rotina'></label><p class='open-question-note'>Resposta aberta: o entrevistador registrará a fala da pessoa em um campo de texto.</p></article>`).join('');updateQuestionCount();}
function updateQuestionCount(){const active=questionDraft.filter(question=>question.active).length;$('question-count').textContent=`${questionDraft.length} cadastrada${questionDraft.length===1?'':'s'} • ${active} ativa${active===1?'':'s'}`;}
function syncQuestionField(target){const card=target.closest('.question-editor');if(!card)return;const question=questionDraft.find(item=>item.id===card.dataset.id);if(!question)return;if(target.classList.contains('q-active'))question.active=target.checked;if(target.classList.contains('q-title'))question.title=target.value;if(target.classList.contains('q-help'))question.help=target.value;card.classList.toggle('inactive',!question.active);const status=card.querySelector('.active-switch span');if(status)status.textContent=question.active?'Ativa na pesquisa':'Oculta na pesquisa';updateQuestionCount();}
async function loadQuestionConfig(){const message=$('question-config-message');message.textContent='Carregando perguntas...';try{const snapshot=await getDoc(doc(db,'settings','diagnostic'));if(snapshot.exists()){const data=snapshot.data();if(Number(data.schemaVersion)>=3&&Array.isArray(data.questions)&&data.questions.length){questionDraft=data.questions.map(normalizeQuestion);}else{questionDraft=cloneDefaults();message.textContent='Modelo atualizado para perguntas abertas. Clique em Salvar alterações para gravar a nova configuração.';}}else{questionDraft=cloneDefaults();}renderQuestionConfig();if(!message.textContent.includes('Modelo atualizado'))message.textContent='Edite, crie, exclua ou ative as perguntas e depois salve as alterações.';}catch(error){console.error(error);questionDraft=cloneDefaults();renderQuestionConfig();message.textContent='Não foi possível carregar a configuração salva. Exibindo as perguntas padrão.';}}
$('login').addEventListener('click',async()=>{const email=$('email').value.trim(),password=$('password').value;$('login-message').textContent='';if(!email||!password){$('login-message').textContent='Informe e-mail e senha.';return;}$('login').disabled=true;$('login').textContent='Entrando...';try{await signInWithEmailAndPassword(auth,email,password);}catch(error){$('login-message').textContent='Não foi possível entrar. Confira o e-mail, a senha e o acesso no Firebase.';console.error(error);}finally{$('login').disabled=false;$('login').textContent='Entrar no painel';}});
$('logout').addEventListener('click',()=>signOut(auth));
$('question-list').addEventListener('input',event=>syncQuestionField(event.target));
$('question-list').addEventListener('change',event=>syncQuestionField(event.target));
$('question-list').addEventListener('click',event=>{const deleteButton=event.target.closest('.q-delete');if(!deleteButton)return;const card=deleteButton.closest('.question-editor');const question=questionDraft.find(item=>item.id===card.dataset.id);if(!question)return;if(!confirm(`Excluir a pergunta "${question.title||'Sem título'}"? A exclusão só será aplicada depois de salvar as alterações.`))return;questionDraft=questionDraft.filter(item=>item.id!==question.id);renderQuestionConfig();$('question-config-message').textContent='Pergunta removida. Clique em Salvar alterações para aplicar.';});
$('add-question').addEventListener('click',()=>{questionDraft.push({id:createQuestionId(),title:'',help:'',type:'open',active:true,order:questionDraft.length});renderQuestionConfig();const cards=document.querySelectorAll('.question-editor');const card=cards[cards.length-1];card?.scrollIntoView({behavior:'smooth',block:'center'});card?.querySelector('.q-title')?.focus();$('question-config-message').textContent='Nova pergunta adicionada. Preencha os campos e salve as alterações.';});
$('select-all-questions').addEventListener('click',()=>{questionDraft.forEach(question=>question.active=true);renderQuestionConfig();});
$('clear-questions').addEventListener('click',()=>{questionDraft.forEach(question=>question.active=false);renderQuestionConfig();});
$('save-questions').addEventListener('click',async()=>{document.querySelectorAll('#question-list input').forEach(element=>syncQuestionField(element));const button=$('save-questions'),message=$('question-config-message');const cleaned=questionDraft.map((question,index)=>normalizeQuestion(question,index));const invalid=cleaned.find(question=>!question.title);if(invalid){message.textContent='Todas as perguntas precisam de um texto.';return;}const activeIds=cleaned.filter(question=>question.active).map(question=>question.id);if(!activeIds.length){message.textContent='Mantenha pelo menos uma pergunta ativa.';return;}button.disabled=true;button.textContent='Salvando...';message.textContent='';try{await setDoc(doc(db,'settings','diagnostic'),{schemaVersion:3,questionMode:'open',questions:cleaned,activeQuestionIds:activeIds,updatedAt:serverTimestamp()},{merge:true});questionDraft=cleaned;renderQuestionConfig();message.textContent='Perguntas salvas. O diagnóstico público já usará esta configuração.';button.textContent='Alterações salvas';setTimeout(()=>button.textContent='Salvar alterações',1600);}catch(error){console.error(error);message.textContent='Não foi possível salvar as perguntas. Confira o acesso do Firebase.';button.textContent='Tentar novamente';}finally{button.disabled=false;}});
$('rows').addEventListener('click',async event=>{const detailButton=event.target.closest('[data-detail]');if(detailButton){const box=$('details');box.textContent=details(diagnostics[Number(detailButton.dataset.detail)]);box.classList.remove('hidden');box.scrollIntoView({behavior:'smooth',block:'nearest'});return;}const deleteButton=event.target.closest('[data-delete]');if(!deleteButton)return;const item=diagnostics[Number(deleteButton.dataset.delete)];if(!confirm(`Excluir o diagnóstico de ${item.business?.name||'este negócio'}? Esta ação não pode ser desfeita.`))return;deleteButton.disabled=true;deleteButton.textContent='Excluindo...';try{await deleteDoc(doc(db,'diagnostics',item.id));diagnostics=diagnostics.filter(diagnostic=>diagnostic.id!==item.id);$('details').classList.add('hidden');render();}catch(error){alert('Não foi possível excluir. Confira as regras do Firestore.');deleteButton.disabled=false;deleteButton.textContent='Excluir';console.error(error);}});
onAuthStateChanged(auth,user=>{const loggedIn=Boolean(user);$('login-view').classList.toggle('hidden',loggedIn);$('panel-view').classList.toggle('hidden',!loggedIn);if(loggedIn){loadDiagnostics();loadQuestionConfig();}else if(unsubscribeDiagnostics){unsubscribeDiagnostics();unsubscribeDiagnostics=undefined;}});
