import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import { collection, deleteDoc, doc, getDoc, getFirestore, onSnapshot, orderBy, query, serverTimestamp, setDoc } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyAPkjFAzWhxaAnsfxd4PGQsFCkurV0u6f4',authDomain:'device-streaming-23f6b787.firebaseapp.com',projectId:'device-streaming-23f6b787',storageBucket:'device-streaming-23f6b787.firebasestorage.app',messagingSenderId:'1084466489845',appId:'1:1084466489845:web:3f1cb241ed0f39914858bc'};
const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getFirestore(app);
const $=id=>document.getElementById(id); const esc=value=>String(value||'—').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const defaultQuestions=[
  {id:'q1',title:'Qual é hoje o maior desafio do negócio?',help:'Escolha o ponto que mais impacta a operação.',options:['Organização do dia a dia','Vendas e clientes','Controle financeiro','Estoque e desperdício','Equipe e atendimento','Outro'],tags:{'Organização do dia a dia':['Processos e rotina'],'Vendas e clientes':['Vendas e relacionamento'],'Controle financeiro':['Financeiro e indicadores'],'Estoque e desperdício':['Estoque e compras'],'Equipe e atendimento':['Equipe e atendimento']}},
  {id:'q2',title:'Como as vendas, pedidos ou serviços são registrados?',help:'Entenda o nível de organização atual.',options:['Caderno / papel','WhatsApp','Planilha','Sistema','Não existe padrão'],tags:{'Caderno / papel':['Processos e rotina'],'WhatsApp':['Processos e rotina'],'Planilha':['Financeiro e indicadores'],'Não existe padrão':['Processos e rotina']}},
  {id:'q3',title:'A pessoa responsável consegue enxergar o resultado mensal?',help:'Lucro, custos e principais gastos.',options:['Sim, com clareza','Mais ou menos','Não consegue acompanhar'],tags:{'Mais ou menos':['Financeiro e indicadores'],'Não consegue acompanhar':['Financeiro e indicadores']}},
  {id:'q4',title:'Há perdas por erro, retrabalho ou falta de informação?',help:'Erros em pedidos, serviços, agenda, caixa ou comunicação.',options:['Frequentemente','Às vezes','Raramente'],tags:{'Frequentemente':['Processos e rotina'],'Às vezes':['Processos e rotina']}},
  {id:'q5',title:'Como são controlados materiais, produtos ou estoque?',help:'Se o negócio não trabalha com estoque, marque a última opção.',options:['De cabeça','Caderno ou planilha','Sistema','Não se aplica'],tags:{'De cabeça':['Estoque e compras'],'Caderno ou planilha':['Estoque e compras']}},
  {id:'q6',title:'Como novos clientes chegam ao negócio?',help:'Identifique a principal fonte atual.',options:['Indicação','Instagram / redes sociais','WhatsApp','Anúncios','Ponto físico','Não acompanho'],tags:{'Não acompanho':['Vendas e relacionamento']}},
  {id:'q7',title:'Existe acompanhamento dos clientes depois da compra?',help:'Retorno, fidelização, lembretes ou ofertas.',options:['Sim, organizado','Às vezes','Não'],tags:{'Às vezes':['Vendas e relacionamento'],'Não':['Vendas e relacionamento']}},
  {id:'q8',title:'Qual melhoria teria maior impacto nos próximos 90 dias?',help:'Use essa resposta para definir a prioridade.',options:['Vender mais','Organizar a operação','Reduzir custos','Controlar melhor o dinheiro','Melhorar o atendimento','Outro'],tags:{'Vender mais':['Vendas e relacionamento'],'Organizar a operação':['Processos e rotina'],'Reduzir custos':['Estoque e compras'],'Controlar melhor o dinheiro':['Financeiro e indicadores'],'Melhorar o atendimento':['Equipe e atendimento']}}
];
let questionDraft=[], diagnostics=[], unsubscribeDiagnostics;
function dateOf(item){return item.clientCreatedAt?new Date(item.clientCreatedAt):item.createdAt?.toDate?.()||new Date();}
function formatDate(item){return dateOf(item).toLocaleDateString('pt-BR',{dateStyle:'short'})+' '+dateOf(item).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});}
function details(item){const answers=(item.answers||[]).map((answer,index)=>`${index+1}. ${answer.question}\nResposta: ${answer.choice}${answer.note?`\nObservação: ${answer.note}`:''}`).join('\n\n');return `${item.business?.name||'Negócio não informado'}\nResponsável: ${item.business?.owner||'—'}\nSegmento: ${item.business?.segment||'—'}\n\n${answers}\n\nPrioridades:\n${(item.priorities||[]).map(priority=>`• ${priority.name}: ${priority.summary}`).join('\n')||'—'}\n\nObservação final:\n${item.finalNote||'—'}`;}
function render(){const todayKey=new Date().toDateString();$('total').textContent=diagnostics.length;$('today').textContent=diagnostics.filter(item=>dateOf(item).toDateString()===todayKey).length;$('segments').textContent=new Set(diagnostics.map(item=>item.business?.segment).filter(Boolean)).size;$('rows').innerHTML=diagnostics.length?diagnostics.map((item,index)=>`<tr><td>${esc(formatDate(item))}</td><td><strong>${esc(item.business?.name)}</strong></td><td>${esc(item.business?.owner)}</td><td>${esc(item.business?.segment)}</td><td>${esc((item.priorities||[]).map(priority=>priority.name).join(', '))}</td><td><button data-detail="${index}">Ver</button> <button class="delete" data-delete="${index}">Excluir</button></td></tr>`).join(''):'<tr><td colspan="6">Ainda não há diagnósticos salvos.</td></tr>';}
function loadDiagnostics(){if(unsubscribeDiagnostics)unsubscribeDiagnostics();unsubscribeDiagnostics=onSnapshot(query(collection(db,'diagnostics'),orderBy('createdAt','desc')),snapshot=>{diagnostics=snapshot.docs.map(doc=>({id:doc.id,...doc.data()}));render();},error=>{$('rows').innerHTML='<tr><td colspan="6">Não foi possível carregar os diagnósticos. Confira as regras do Firestore.</td></tr>';console.error(error);});}
function cloneTags(tags){return Object.fromEntries(Object.entries(tags||{}).map(([option,categories])=>[option,Array.isArray(categories)?[...categories]:[]]));}
function cloneDefaults(){return defaultQuestions.map(question=>({...question,options:[...question.options],tags:cloneTags(question.tags),active:true}));}
function createQuestionId(){return 'q_custom_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);}
function normalizeQuestion(question,index=0){const fallback=defaultQuestions.find(item=>item.id===question?.id);const options=Array.isArray(question?.options)?question.options.map(option=>String(option).trim()).filter(Boolean):fallback?[...fallback.options]:[];return {id:String(question?.id||createQuestionId()),title:String(question?.title??fallback?.title??'').trim(),help:String(question?.help??fallback?.help??'').trim(),options,tags:cloneTags(question?.tags||fallback?.tags||{}),active:question?.active!==false,order:Number.isFinite(question?.order)?question.order:index};}
function renderQuestionConfig(){const list=$('question-list');list.innerHTML=questionDraft.map((question,index)=>`<article class='question-editor ${question.active?'':'inactive'}' data-id='${html(question.id)}'><div class='question-editor-top'><div><span class='question-index'>PERGUNTA ${index+1}</span><label class='active-switch'><input class='q-active' type='checkbox' ${question.active?'checked':''}><span>${question.active?'Ativa no diagnóstico':'Oculta no diagnóstico'}</span></label></div><button class='danger-btn q-delete' type='button'>Excluir</button></div><label>Texto da pergunta<input class='q-title' type='text' value='${html(question.title)}' placeholder='Digite a pergunta'></label><label>Texto de apoio <small>(opcional)</small><input class='q-help' type='text' value='${html(question.help)}' placeholder='Ex.: escolha a opção que melhor representa o negócio'></label><label>Opções de resposta <small>(uma por linha)</small><textarea class='q-options' rows='4' placeholder='Opção 1&#10;Opção 2'>${html(question.options.join('\n'))}</textarea></label></article>`).join('');updateQuestionCount();}
function updateQuestionCount(){const active=questionDraft.filter(question=>question.active).length;$('question-count').textContent=`${questionDraft.length} cadastrada${questionDraft.length===1?'':'s'} • ${active} ativa${active===1?'':'s'}`;}
function syncQuestionField(target){const card=target.closest('.question-editor');if(!card)return;const question=questionDraft.find(item=>item.id===card.dataset.id);if(!question)return;if(target.classList.contains('q-active'))question.active=target.checked;if(target.classList.contains('q-title'))question.title=target.value;if(target.classList.contains('q-help'))question.help=target.value;if(target.classList.contains('q-options'))question.options=target.value.split(/\r?\n/).map(option=>option.trim()).filter(Boolean);card.classList.toggle('inactive',!question.active);const status=card.querySelector('.active-switch span');if(status)status.textContent=question.active?'Ativa no diagnóstico':'Oculta no diagnóstico';updateQuestionCount();}
async function loadQuestionConfig(){const message=$('question-config-message');message.textContent='Carregando perguntas...';try{const snapshot=await getDoc(doc(db,'settings','diagnostic'));if(snapshot.exists()){const data=snapshot.data();if(Array.isArray(data.questions)&&data.questions.length){questionDraft=data.questions.map(normalizeQuestion);}else{const activeIds=Array.isArray(data.activeQuestionIds)?data.activeQuestionIds:defaultQuestions.map(question=>question.id);questionDraft=cloneDefaults().map(question=>({...question,active:activeIds.includes(question.id)}));}}else{questionDraft=cloneDefaults();}renderQuestionConfig();message.textContent='Edite, crie, exclua ou ative as perguntas e depois salve as alterações.';}catch(error){console.error(error);questionDraft=cloneDefaults();renderQuestionConfig();message.textContent='Não foi possível carregar a configuração salva. Exibindo as perguntas padrão.';}}
$('login').addEventListener('click',async()=>{const email=$('email').value.trim(),password=$('password').value;$('login-message').textContent='';if(!email||!password){$('login-message').textContent='Informe e-mail e senha.';return;}$('login').disabled=true;$('login').textContent='Entrando...';try{await signInWithEmailAndPassword(auth,email,password);}catch(error){$('login-message').textContent='Não foi possível entrar. Confira o e-mail, a senha e o acesso no Firebase.';console.error(error);}finally{$('login').disabled=false;$('login').textContent='Entrar no painel';}});
$('logout').addEventListener('click',()=>signOut(auth));
$('question-list').addEventListener('input',event=>syncQuestionField(event.target));
$('question-list').addEventListener('change',event=>syncQuestionField(event.target));
$('question-list').addEventListener('click',event=>{const deleteButton=event.target.closest('.q-delete');if(!deleteButton)return;const card=deleteButton.closest('.question-editor');const question=questionDraft.find(item=>item.id===card.dataset.id);if(!question)return;if(!confirm(`Excluir a pergunta "${question.title||'Sem título'}"? A exclusão só será aplicada depois de salvar as alterações.`))return;questionDraft=questionDraft.filter(item=>item.id!==question.id);renderQuestionConfig();$('question-config-message').textContent='Pergunta removida. Clique em Salvar alterações para aplicar.';});
$('add-question').addEventListener('click',()=>{questionDraft.push({id:createQuestionId(),title:'',help:'',options:['Sim','Não'],tags:{},active:true,order:questionDraft.length});renderQuestionConfig();const cards=document.querySelectorAll('.question-editor');const card=cards[cards.length-1];card?.scrollIntoView({behavior:'smooth',block:'center'});card?.querySelector('.q-title')?.focus();$('question-config-message').textContent='Nova pergunta adicionada. Preencha os campos e salve as alterações.';});
$('select-all-questions').addEventListener('click',()=>{questionDraft.forEach(question=>question.active=true);renderQuestionConfig();});
$('clear-questions').addEventListener('click',()=>{questionDraft.forEach(question=>question.active=false);renderQuestionConfig();});
$('save-questions').addEventListener('click',async()=>{document.querySelectorAll('#question-list input,#question-list textarea').forEach(element=>syncQuestionField(element));const button=$('save-questions'),message=$('question-config-message');const cleaned=questionDraft.map((question,index)=>{const normalized=normalizeQuestion(question,index);normalized.tags=Object.fromEntries(normalized.options.filter(option=>normalized.tags[option]?.length).map(option=>[option,normalized.tags[option]]));return normalized;});const invalid=cleaned.find(question=>!question.title||question.options.length<2);if(invalid){message.textContent='Todas as perguntas precisam de um texto e pelo menos 2 opções de resposta.';return;}const activeIds=cleaned.filter(question=>question.active).map(question=>question.id);if(!activeIds.length){message.textContent='Mantenha pelo menos uma pergunta ativa.';return;}button.disabled=true;button.textContent='Salvando...';message.textContent='';try{await setDoc(doc(db,'settings','diagnostic'),{schemaVersion:2,questions:cleaned,activeQuestionIds:activeIds,updatedAt:serverTimestamp()},{merge:true});questionDraft=cleaned;renderQuestionConfig();message.textContent='Perguntas salvas. O diagnóstico público já usará esta configuração.';button.textContent='Alterações salvas';setTimeout(()=>button.textContent='Salvar alterações',1600);}catch(error){console.error(error);message.textContent='Não foi possível salvar as perguntas. Confira o acesso do Firebase.';button.textContent='Tentar novamente';}finally{button.disabled=false;}});
$('rows').addEventListener('click',async event=>{const detailButton=event.target.closest('[data-detail]');if(detailButton){const box=$('details');box.textContent=details(diagnostics[Number(detailButton.dataset.detail)]);box.classList.remove('hidden');box.scrollIntoView({behavior:'smooth',block:'nearest'});return;}const deleteButton=event.target.closest('[data-delete]');if(!deleteButton)return;const item=diagnostics[Number(deleteButton.dataset.delete)];if(!confirm(`Excluir o diagnóstico de ${item.business?.name||'este negócio'}? Esta ação não pode ser desfeita.`))return;deleteButton.disabled=true;deleteButton.textContent='Excluindo...';try{await deleteDoc(doc(db,'diagnostics',item.id));diagnostics=diagnostics.filter(diagnostic=>diagnostic.id!==item.id);$('details').classList.add('hidden');render();}catch(error){alert('Não foi possível excluir. Confira as regras do Firestore.');deleteButton.disabled=false;deleteButton.textContent='Excluir';console.error(error);}});
onAuthStateChanged(auth,user=>{const loggedIn=Boolean(user);$('login-view').classList.toggle('hidden',loggedIn);$('panel-view').classList.toggle('hidden',!loggedIn);if(loggedIn){loadDiagnostics();loadQuestionConfig();}else if(unsubscribeDiagnostics){unsubscribeDiagnostics();unsubscribeDiagnostics=undefined;}});
