import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import { collection, deleteDoc, doc, getFirestore, onSnapshot, orderBy, query } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyAPkjFAzWhxaAnsfxd4PGQsFCkurV0u6f4',authDomain:'device-streaming-23f6b787.firebaseapp.com',projectId:'device-streaming-23f6b787',storageBucket:'device-streaming-23f6b787.firebasestorage.app',messagingSenderId:'1084466489845',appId:'1:1084466489845:web:3f1cb241ed0f39914858bc'};
const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getFirestore(app);
const $=id=>document.getElementById(id); const esc=value=>String(value||'—').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let diagnostics=[], unsubscribeDiagnostics;
function dateOf(item){return item.clientCreatedAt?new Date(item.clientCreatedAt):item.createdAt?.toDate?.()||new Date();}
function formatDate(item){return dateOf(item).toLocaleDateString('pt-BR',{dateStyle:'short'})+' '+dateOf(item).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});}
function details(item){const answers=(item.answers||[]).map((answer,index)=>`${index+1}. ${answer.question}\nResposta: ${answer.choice}${answer.note?`\nObservação: ${answer.note}`:''}`).join('\n\n');return `${item.business?.name||'Negócio não informado'}\nResponsável: ${item.business?.owner||'—'}\nSegmento: ${item.business?.segment||'—'}\n\n${answers}\n\nPrioridades:\n${(item.priorities||[]).map(priority=>`• ${priority.name}: ${priority.summary}`).join('\n')||'—'}\n\nObservação final:\n${item.finalNote||'—'}`;}
function render(){const todayKey=new Date().toDateString();$('total').textContent=diagnostics.length;$('today').textContent=diagnostics.filter(item=>dateOf(item).toDateString()===todayKey).length;$('segments').textContent=new Set(diagnostics.map(item=>item.business?.segment).filter(Boolean)).size;$('rows').innerHTML=diagnostics.length?diagnostics.map((item,index)=>`<tr><td>${esc(formatDate(item))}</td><td><strong>${esc(item.business?.name)}</strong></td><td>${esc(item.business?.owner)}</td><td>${esc(item.business?.segment)}</td><td>${esc((item.priorities||[]).map(priority=>priority.name).join(', '))}</td><td><button data-detail="${index}">Ver</button> <button class="delete" data-delete="${index}">Excluir</button></td></tr>`).join(''):'<tr><td colspan="6">Ainda não há diagnósticos salvos.</td></tr>';}
function loadDiagnostics(){if(unsubscribeDiagnostics)unsubscribeDiagnostics();unsubscribeDiagnostics=onSnapshot(query(collection(db,'diagnostics'),orderBy('createdAt','desc')),snapshot=>{diagnostics=snapshot.docs.map(doc=>({id:doc.id,...doc.data()}));render();},error=>{$('rows').innerHTML='<tr><td colspan="6">Não foi possível carregar os diagnósticos. Confira as regras do Firestore.</td></tr>';console.error(error);});}
$('login').addEventListener('click',async()=>{const email=$('email').value.trim(),password=$('password').value;$('login-message').textContent='';if(!email||!password){$('login-message').textContent='Informe e-mail e senha.';return;}$('login').disabled=true;$('login').textContent='Entrando...';try{await signInWithEmailAndPassword(auth,email,password);}catch(error){$('login-message').textContent='Não foi possível entrar. Confira o e-mail, a senha e o acesso no Firebase.';console.error(error);}finally{$('login').disabled=false;$('login').textContent='Entrar no painel';}});
$('logout').addEventListener('click',()=>signOut(auth));
$('rows').addEventListener('click',async event=>{const detailButton=event.target.closest('[data-detail]');if(detailButton){const box=$('details');box.textContent=details(diagnostics[Number(detailButton.dataset.detail)]);box.classList.remove('hidden');box.scrollIntoView({behavior:'smooth',block:'nearest'});return;}const deleteButton=event.target.closest('[data-delete]');if(!deleteButton)return;const item=diagnostics[Number(deleteButton.dataset.delete)];if(!confirm(`Excluir o diagnóstico de ${item.business?.name||'este negócio'}? Esta ação não pode ser desfeita.`))return;deleteButton.disabled=true;deleteButton.textContent='Excluindo...';try{await deleteDoc(doc(db,'diagnostics',item.id));diagnostics=diagnostics.filter(diagnostic=>diagnostic.id!==item.id);$('details').classList.add('hidden');render();}catch(error){alert('Não foi possível excluir. Confira as regras do Firestore.');deleteButton.disabled=false;deleteButton.textContent='Excluir';console.error(error);}});
onAuthStateChanged(auth,user=>{const loggedIn=Boolean(user);$('login-view').classList.toggle('hidden',loggedIn);$('panel-view').classList.toggle('hidden',!loggedIn);if(loggedIn)loadDiagnostics();else if(unsubscribeDiagnostics){unsubscribeDiagnostics();unsubscribeDiagnostics=undefined;}});
